# Generated by Django 2.1.7 on 2019-02-23 11:40

from django.db import migrations, models
import sqlparse


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.TextField(db_column='Ruc')),
                ('numero', models.TextField(db_column='Numero')),
                ('identificacion', models.TextField(blank=True, null=True)),
                ('fecha', models.TextField()),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('subtotal', models.TextField(blank=True, null=True)),
                ('descuento', models.TextField(blank=True, null=True)),
                ('iva', models.TextField(blank=True, null=True)),
                ('total', models.TextField(blank=True, null=True)),
                ('anulada', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comprobante',
            },
        ),
        migrations.AlterUniqueTogether(
            name='comprobante',
            unique_together={('ruc', 'numero')},
        ),
        migrations.RunSQL(
            sql=sqlparse.split('''
                INSERT INTO comprobante (Ruc, Numero, identificacion, fecha, direccion, telefono, email, subtotal, descuento, iva, total, anulada) VALUES ('1790016919001', '006111000362159', '1792231612001', '2019-01-29', 'HOMERO SALAS S/N Y AV. DE LA PRENSA', '2996500', '', '17.54000', '0.00000', '1.47000', '19.01000', '0');
                INSERT INTO comprobante (Ruc, Numero, identificacion, fecha, direccion, telefono, email, subtotal, descuento, iva, total, anulada) VALUES ('1791414713001', '001001000039698', '1792231612001', '2019-01-29', 'Pichincha Quito Pintag Vía Pifo SN y Vía Alangasi', null, '', '151.65000', '0.00000', '7.40000', '159.05000', '0');
                INSERT INTO comprobante (Ruc, Numero, identificacion, fecha, direccion, telefono, email, subtotal, descuento, iva, total, anulada) VALUES ('1792252903001', '002004000587976', '1792231612001', '2019-01-17', 'TABABELA - CORREDOR ALPACHACA, LOTE 18 - NUEVO AEROPUERTO INTERNACIONAL', '2222222', '', '8.99000', '2.01000', '0.00000', '8.99000', '0');
                INSERT INTO comprobante (Ruc, Numero, identificacion, fecha, direccion, telefono, email, subtotal, descuento, iva, total, anulada) VALUES ('1792252903001', '003001000586678', '1792231612001', '2019-01-17', 'AV. AMAZONAS Y AV. DE LA PRENSA', '2222222', '', '7.99000', '0.01000', '0.00000', '7.99000', '0');
                INSERT INTO comprobante (Ruc, Numero, identificacion, fecha, direccion, telefono, email, subtotal, descuento, iva, total, anulada) VALUES ('1792599512001', '001001000003704', '1792231612001', '2019-01-21', 'PASAJE S/N N3-62 Y SIMON BOLIVAR, PUENTE 9 URBANIZACION ARMENIA 1 VALLE DE LOS CHILLOS- QUITO -ECUADOR ', '6007470 ext 102', '', '60.00000', '0.00000', '7.20000', '67.20000', '0');
                INSERT INTO comprobante (Ruc, Numero, identificacion, fecha, direccion, telefono, email, subtotal, descuento, iva, total, anulada) VALUES ('2290324907001', '001001000001803', '1792231612001', '2019-01-17', 'EL COCA ', '062881715', '', '224.10000', '24.90000', '26.89000', '250.99000', '0');
            ''')
        )
    ]
