# Generated by Django 2.1.7 on 2019-02-23 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_detalles', '0002_auto_20190223_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantedetalles',
            name='comprobante_numero',
            field=models.ForeignKey(db_column='comprobante_Numero', on_delete=django.db.models.deletion.CASCADE, related_name='Numero', to='comprobante.Comprobante'),
        ),
        migrations.AlterField(
            model_name='comprobantedetalles',
            name='comprobante_ruc',
            field=models.ForeignKey(db_column='comprobante_Ruc', on_delete=django.db.models.deletion.CASCADE, related_name='Ruc', to='comprobante.Comprobante'),
        ),
    ]
